export const MESSAGES = {
    GET_SUCCEED: 'Get successfully',
    CREATED_SUCCEED: 'Created successfully',
    DELETE_SUCCEED: 'Delete successfully',
    UPDATE_SUCCEED: 'Update successfully',
    CREATED_FLASHCARD_FAIL: 'Created Flashcard fail',
    CREATED_QUIZ_FAIL: 'Created Quiz fail',
    CREATE_CONTENT_FAIL: 'Created content fail',
    CANNOT_GET_DATA: 'Cannot get data',
    CANNOT_CREATE: 'Cannot create',
    CANNOT_DELETE: 'Cannot delete',
    CANNOT_UPDATE: 'Cannot update',
    CANNOT_UPDATE_OR_CREATE: 'cannot_update_or_create',
    REGISTER_SUCCESS: 'Register successfully, please check your email',
    INSERT_SUCCEED: 'Insert successfully',
    NO_CONTENT: 'No content',
    OK: 'ok',
    PERMISSION_DENIED: 'Permission denied',
    UNAUTHORIZED: 'Email or password is incorrect',
    INVALID_TOKEN: 'Invalid token',
    CANNOT_UPLOAD_IMAGE: 'cannot_upload_image',
    UPLOAD_SUCCESS: 'Upload successfully',
    INVALID_QUERY: 'invalid_query',
    INVALID_PARAM: 'invalid_param',
    UNAUTHORIZED_ADMIN: 'unauthorized_admin_request',
    NOT_FOUND_USER: 'This account does not exist',
    NOT_FOUND: 'Not found',
    INVALID_CODE: 'Invalid code',
    VERIFY_SUCCESS: 'Verify successfully',
    CONFIRMED_ACCOUNT: 'This account is confirmed',
    UNCONFIRMED_ACCOUNT: 'Please verify your email',
    ROLE_NOT_FOUND: 'role_not_found',
    EMAIL_EXISTS: 'Email or username exist',
    RESEND_SUCCESS: 'Resend successfully',
    SENT_EMAIL_TO_RECOVER_PASSWORD: 'Email sent',
    FAVORITE_IS_EXITS: 'Favorite is exits',
    NOT_FOUND_TONE: 'Tone isn`t found',
    NOT_FOUND_CATEGORY: 'Category isn`t found',
    NOT_FOUND_USER_POST: 'Not found',
    YOU_ALREADY_COMMENT: 'you have already commented',
    ERRO_FILE: 'Error in timestamp file',
    NOT_AVAILABLE:'Your account is not available for this sign in method',
    USED:'Title has been used',
    CHECK_SUCCEED: 'Check successfully',
  };
  